config/routes.rb
Rails.application.routes.draw do

  resources :tools
  resources :users, only: [:new, :create, :show]
  resources :categories, only: [:index, :show]
  root to: 'users#index'

  namespace "admin" do
    resources :categories
    resources :tools
  end

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :tools
end

app/models/tool.rb
class Tool < ActiveRecord::Base
  validates :name, :presence => true
  validates :price, :presence => true
  validates :quantity, :presence => true
  belongs_to :user
  belongs_to :category

  def formatted_price
    price/100.0
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :tools
  has_secure_password
  enum role: %w(default admin)
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :require_admin #will run each time

   def require_admin #this is our authorization
     render file: '/public/404' unless current_admin?
   end

end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    byebug
    @category = Category.new(category_params)
    if @category.save
      redirect_to admin_category_path(@category)
    else
      render :new
    end
  end

  def show
    @category = Category.find(params[:id])
    @category_tools = @category.tools
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update #this actually is being called, using new. need to fix
    @category = Category.find(params[:id])
    if @category.update(category_params)
      redirect_to admin_category_path(@category)
    else
      render :edit
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to admin_categories_path
  end

private

  def category_params
    params.require(:category).permit(:name)
  end

end

app/controllers/admin/tools_controller.rb
class Admin::ToolsController < Admin::BaseController

  def index
    @tools = Tool.all
    last_tool = current_user.tools.order(:created_at).last
    session[:most_recent_tool_id] = last_tool
    render 'index'
  end

  def show
    @tool = Tool.find(params[:id])
  end

  def new
    @tool = Tool.new
  end

  def create
    @tool = Tool.new(tool_params)
    if @tool.save #if passed, do... save checks validations to see if it can be created
      flash[:notice] = "You created a tool!"
      redirect_to admin_tool_path(@tool.id) #redirect to @tool will work, but nice to be more explicit
    else
      flash[:error] = @tool.errors.full_messages.join(", ")
      render :new #render does not make new request
    end
    #generate new, add attributes to tool, save tool, if saves in the db, will send user to view tool, no save then render new view
  end

  def edit
    @tool = Tool.find(params[:id])
  end

  def update
    @tool = Tool.find(params[:id])
    if @tool.update(tool_params)
      redirect_to admin_tool_path(@tool.id)
    else
      render :edit
    end
  end

  def destroy
    @tool = Tool.find(params[:id]) 
    @tool.destroy
    redirect_to admin_tools_path
  end

  private

  def tool_params #more secure
    params.require(:tool).permit(:name, :quantity, :price, :category_id) #tool key, only let specific attributes be changes
    #allows things from params into object
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception
  helper_method :most_recent_tool, :current_admin?, :current_tool_summary, :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_admin?
    current_user && current_user.admin?
  end

  def current_tool_summary
    all_tools = Tool.all.count
    session[:current_tool_count] = all_tools
    sum_of_price = Tool.sum(:price)
    session[:current_potential_revenue] = sum_of_price
    "Tool count-#{session[:current_tool_count]} Potential revenue-#{session[:current_potential_revenue]}"
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @category_tools = @category.tools
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    @user = User.find_by(username: params[:session][:username])
    @user && @user.authenticate(params[:session][:password]) #user exists in db and pw is ok
    session[:user_id] = @user.id

    #if @user && @user.authenticate(params[:session][:password]) #user exists in db and pw is ok
    # session[:user_id] = @user.id #could have this in model, but in string for the path. Would call user.dashboard path
      # if user.admin?
        #redirect to admin_dashboard_path
      #else
        #redirect_to user_path(user)
    #else
      #render:new

    redirect_to @user
  end

  def new

  end

  def destroy
    session.clear
    redirect_to root_path
  end

end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController
  #before_action :find_tool, only [:show, :edit, :update] to do the find tool a lot, put actual method in private area 

  def index
    user = current_user
    if user.nil?
      render :text => "There are no tools"
    else
      @tools = user.tools.all
      last_tool = current_user.tools.order(:created_at).last
      session[:most_recent_tool_id] = last_tool
      render 'index'
    end
  end

  def show
    user = current_user
    @tool = user.tools.find(params[:id])
  end

  def new
    user = current_user
    @tool = user.tools.new
  end

  def create
    user = current_user
    @tool = user.tools.new(tool_params)
    #need something with Category here
    # @tool = Tool.new(tool_params)
    if @tool.save #if passed, do... save checks validations to see if it can be created
      flash[:notice] = "You created a tool!"
      redirect_to tool_path(@tool.id) #redirect to @tool will work, but nice to be more explicit
    else
      flash[:error] = @tool.errors.full_messages.join(", ")
      render :new #render does not make new request
    end
    #generate new, add attributes to tool, save tool, if saves in the db, will send user to view tool, no save then render new view
  end

  def edit
    user = current_user
    @tool = user.tools.find(params[:id])
  end

  def update
    user = current_user
    @tool = user.tools.find(params[:id])
    if @tool.update(tool_params)
      redirect_to tool_path(@tool.id)
    else
      render :edit
    end
  end

  def destroy
    user = current_user
    @tool = user.tools.find(params[:id]) #same as Tool.destroy(params[:id])
    @tool.destroy #activerecord method
    redirect_to tools_path
  end

  private

  def tool_params #more secure
    params.require(:tool).permit(:name, :quantity, :price, :category_id) #tool key, only let specific attributes be changes
    #allows things from params into object
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index

  end

  def new

  end

  def create
    user = User.create(user_params) #could do user.new, then if user.save redirect, else render: new. Probably want ivar
    session[:user_id] = user.id
    redirect_to user
  end

  def show
    @user = current_user
  end

private

  def user_params
    params.require(:user).permit(:username, :password) #no role bc we dont want user to change it
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/categories/edit.html.erb
<h1>Update Category</h1>

<%= form_for([:admin, @category]) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/admin/categories/index.html.erb
<div id="admin_categories">

<h1>All Categories</h1>

  <% @categories.each do |category|  %>
    <%= link_to category.name, admin_category_path(category) %>
  <% end %>
</div>

app/views/admin/categories/new.html.erb
<h1>Create Category</h1>

<%#= form_for(:category, url: admin_categories_path) do |f| %>
<%= form_for([:admin, @category]) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/admin/categories/show.html.erb
<h1><%= @category.name%></h1>

<%= link_to "Delete Category", admin_category_path(@category), method: "delete" %>

<h3>Tools Associated with this Category:</h3>

<% @category_tools.each do |tool|  %>

  <%= tool.name  %>

<% end %>

app/views/admin/tools/edit.html.erb
<%= form_for(@tool, url: admin_tool_path(@tool)) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :quantity %>
  <%= f.text_field :quantity %>
  <%= f.label :price %>
  <%= f.text_field :price %>
  <%= f.submit %>
<% end %>

app/views/admin/tools/index.html.erb
<h1> All Tools </h1>

<% @tools.each do |tool| %>
  <h3><%= tool.name %> - <%= tool.quantity %></h3>
<% end %>

app/views/admin/tools/new.html.erb
<%= form_for @tool do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :quantity %>
  <%= f.text_field :quantity %>
  <%= f.label :price %>
  <%= f.text_field :price %>
  <%= select("tool", :category_id, Category.all.collect {|c| [ c.name, c.id ] }, {prompt: 'Select Category'}) %>
  <%= f.submit %>
<% end %>

app/views/admin/tools/show.html.erb
<h1>Tool</h1>

<div class = "tool_info">
<%= @tool.name %> - <%= @tool.quantity %>
<%= @tool.formatted_price %>
<%= link_to "Delete Tool", admin_tool_path(@tool), method: "delete" %>
</div>

app/views/categories/index.html.erb
<h1>All Categories</h1>

  <% @categories.each do |category|  %>
    <%= link_to category.name, category_path(category) %>
  <% end %>

app/views/categories/show.html.erb
<h1><%= @category.name%></h1>


<h3>Tools Associated with this Category:</h3>

<% @category_tools.each do |tool|  %>

  <%= tool.name  %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ToolChest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% flash.each do |type, message|  %>
    <%= content_tag :div, message, class: "flash #{type}" %>
  <% end  %>
  <p>
    <strong>Current Sessions Tool Summary:</strong> <%= current_tool_summary %>
  </p>
<%= yield %>

</body>
</html>

app/views/tools/_form.html.erb
<%= form_for @tool do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :quantity %>
  <%= f.text_field :quantity %>
  <%= f.label :price %>
  <%= f.text_field :price %>
  <%= f.submit %>
<% end %>

app/views/tools/edit.html.erb
<%= render "form" %>

app/views/tools/index.html.erb
<h1> All Tools </h1>

<% @tools.each do |tool| %>
  <h3><%= tool.name %> - <%= tool.quantity %> <%= link_to "Link to View #{tool.name}", tool_path(tool.id) %></h3>
<% end %>

<p>
  <% if session[:most_recent_tool_id].nil?  %>
    <%= "No new tools!" %>
  <% else  %>
    <strong>Newest tool: </strong><%= session[:most_recent_tool_id] %>
  <% end %>
</p>

app/views/tools/new.html.erb
<%= form_for @tool do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :quantity %>
  <%= f.text_field :quantity %>
  <%= f.label :price %>
  <%= f.text_field :price %>
  <%= f.collection_select(:category_id, Category.all, :id, :name, {prompt: 'Select Category'}) %>
  <%= f.submit %>
<% end %>

app/views/tools/show.html.erb
<h1>Tool</h1>

<div class = "tool_info">
<%= "Name: #{@tool.name}" %> - <%= "Quantity: #{@tool.quantity}" %>
<%= "Price: #{@tool.formatted_price}" %>
<% if @tool.category.nil?  %>
  <%= "No category chosen" %>
<% else %>
  <%= "Category: #{@tool.category.name}" %>
<% end %>
<%= link_to "Destroy #{@tool.name}", tool_path(@tool.id), method: "delete" %>
<%= link_to "Update #{@tool.name}", edit_tool_path(@tool.id) %>
</div>

<!-- override get method  -->

<!-- tool_path part is far left in rake routes -->
<!-- can do , class: "task" for styles -->

app/views/users/index.html.erb
<h1>Main Page</h1>

<%= link_to "register", new_user_path %>
<%= link_to "login", login_path %>
<%= link_to "logout", logout_path, method: :delete %>

app/views/users/new.html.erb
<h1>Login New User</h1>

<%= form_for(User.new) do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.submit "Create Account" %>
<% end  %>

app/views/users/show.html.erb
<h1><%= @user.username.capitalize %>'s Page!</h1> <br/>
Hello <%= @user.username.capitalize %>

<h3>Here are your tools:</h3>

<ol>
  <% @user.tools.each do |tool|  %>
    <li><%= tool.name %></li>
  <% end %>
</ol>